// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.2.3.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "ch.qos.logback" % "logback-classic" % "1.1.7",
  "ch.qos.logback" % "logback-core" % "1.1.7",
  "com.fasterxml.jackson.core" % "jackson-annotations" % "2.7.6",
  "com.fasterxml.jackson.core" % "jackson-core" % "2.7.6",
  "com.fasterxml.jackson.core" % "jackson-databind" % "2.7.6",
  "com.fasterxml.jackson.datatype" % "jackson-datatype-jdk8" % "2.7.6",
  "com.fasterxml.jackson.datatype" % "jackson-datatype-jsr310" % "2.7.6",
  "com.ning" % "async-http-client" % "1.9.11",
  "com.typesafe" % "config" % "1.3.0",
  "com.typesafe.play" % "play-datacommons_2.11" % "2.5.9",
  "com.typesafe.play" % "play-functional_2.11" % "2.5.9",
  "com.typesafe.play" % "play-iteratees_2.11" % "2.5.9",
  "com.typesafe.play" % "play-json_2.11" % "2.5.9",
  "io.netty" % "netty" % "3.10.0.Final",
  "joda-time" % "joda-time" % "2.9.4",
  "net.databinder.dispatch" % "dispatch-core_2.11" % "0.11.3",
  "org.joda" % "joda-convert" % "1.8.1",
  "org.scala-lang.modules" % "scala-xml_2.11" % "1.0.1",
  "org.scala-stm" % "scala-stm_2.11" % "0.7",
  "org.scoverage" % "scalac-scoverage-plugin_2.11" % "1.1.1",
  "org.scoverage" % "scalac-scoverage-runtime_2.11" % "1.1.1",
  "org.slf4j" % "slf4j-api" % "1.7.21"
)
// LIBRARY_DEPENDENCIES_HASH 28f5705206426f26a96e37b6e9b9261786bf5f8a
